services:
  - type: web
    name: helicopters-sp-frontend
    runtime: static
    buildCommand: yarn install && yarn build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://helicopters-sp-backend.onrender.com
